# Generated by Django 3.2.6 on 2021-09-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='kind',
            field=models.CharField(blank=True, choices=[('W', 'Warning'), ('I', 'info'), ('D', 'danger'), ('S', 'Success')], default='', max_length=1, null=True),
        ),
    ]
